apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: pyspider-#uuid#
  name: pyspider-#uuid#
spec:
  replicas: 1
  selector:
    app: pyspider-#uuid#
  template:
    metadata:
      labels:
        app: pyspider-#uuid#
    spec:
      containers:
      - image: registry.dataos.io/guestbook/pyspider
        imagePullPolicy: IfNotPresent
        name: pyspider
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  replicas: 0
